version: "3"
services:
  db_estudo:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - 27018:27017
    volumes:
      - .:/usr/app

  app_estudo:
    build: .
    command: npm start
    container_name: web
    restart: always
    depends_on:
      - db_estudo
    ports:
      - 3001:8080
